name: Continuous integration

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Build project
        run: mvn clean install

      - name: Run tests
        run: mvn verify -Dspring.profiles=test

      - name: Generate JaCoCo reports
        run: mvn test -Dspring.profiles=test

      - name: Upload JaCoCo reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: back/target/site/jacoco/*

  frontest-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
          
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
            node-version: 16
          
       - name: Install dependencies
         run: npm install
          
       - name: Run tests
         run: npm run test:ci
          
       - name: Generate Karma reports
         run: npm run test -- --no-watch --code-coverage
          
       - name: Upload Karma reports
         uses: actions/upload-artifact@v4
         with:
            name: karma-reports
            path: front/coverage/bobapp/*
  
  deploy-back-and-front-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Angular Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./front
          file: front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp:${{github.run_number}}
        

      - name: Build and push Spring Boot Docker image
        id: build-and-push-backend
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/back:latest . -f back/Dockerfile
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/back:latest
  



