name: Cantinues integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backen-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11

      - name: Build project
        run: mvn clean install

      - name: Run tests
        run: mvn verify -Dspring.profiles=test

      - name: Generate JaCoCo reports
        run: mvn test-coverage -Dspring.profiles=test

      - name: Upload JaCoCo reports
        uses: actions/upload-artifact@v4
        with:
            name: jacoco-reports
            path: target/site/jacoco/coverage.xml

