name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  deploy-back-and-front-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Angular Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./front
          file: front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bobappfront:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/bobappfront:${{github.run_number}}
        

      - name: Build and push Spring Boot Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./back
          file: back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bobappback:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/bobappback:${{github.run_number}}
  



